### PR TITLE
Gtime port

### PR DESCRIPTION
**Pull request by robotski**
This is my first port, please let me know if anything's not right!

### CODE REVIEW

**Comment by robotski** [comment]
Poudriere build logs:
[gtime-1.9.log-12-4-amd64.log](https://github.com/outpaddling/freebsd-ports-wip/files/12554632/gtime-1.9.log-12-4-amd64.log)
[gtime-1.9.log-12-4-i386.log](https://github.com/outpaddling/freebsd-ports-wip/files/12554633/gtime-1.9.log-12-4-i386.log)

**Comment by outpaddling** [comment]
Looks quite good.  I'd suggest poudriere testing on 12.x and 13.x in the future.  There are often failures due to clang differences and occasionally for other reasons.  14.0-beta1 is coming shortly as well.

**Comment by outpaddling** [comment]
Have you considered creating a symlink to prefix/bin/time?   I would imaging that people who choose to install this port want the "time" command to use it so they don't need hacks like

```
if [ $(uname) = FreeBSD ]; then
    time=gtime
else
    time=time
fi
```

**Comment by robotski** [comment]
I'll be sure to run future poudriere builds on 13 or 14, then.

Had not considered the symlink, since the other ports of GNU utilities that have the same name as something in base all install with the prefix only. Based a lot of my port on misc/gnu-watch, misc/gnuls, and devel/gmake.

**Comment by outpaddling** [comment]
I would test on *all* supported releases, if possible.  You can run older releases in a jail on a newer host.

The symlink argument is reasonable.  Just thought I'd check.

**Pull request merged**
